### ISSUE TITLE
Task

### ISSUE THREAD

**Issue by JohnKhandygo** [ADsty/uniq#1]
**Общая формулировка**

Разработать консольную утилиту, реализующую указанную в задании функциональность, на языках Java и/или Kotlin. При проектировании использовать объектно-ориентированный подход. Разработать автоматические тесты для отдельных частей программы. Написанный код держать в отдельном проекте или модуле в репозитории на GitHub.

**uniq**

Объединение последовательностей одинаковых идущих подряд строк в файле в одну:
- file задаёт имя входного файла. Если параметр отсутствует, следует считывать текст с консоли.
- Флаг -o ofile  задаёт имя выходного файла. Если параметр отсутствует, следует выводить результаты на консоль.
- Флаг -i означает, что при сравнении строк следует не учитывать регистр символов.
- Флаг -s N означает, что при сравнении строк следует игнорировать первые N символов каждой строки. Выводить нужно первую строку.
- Флаг -u означает, что следует выводить в качестве результата только уникальные строки.
- Флаг -с означает, что перед каждой строкой вывода следует вывести количество строк, которые были заменены данной (т.е. если во входных данных было 2 одинаковые строки, в выходных данных должна быть одна с префиксом “2”).

Command line: uniq [-i] [-u] [-c] [-s num] [-o ofile] [file]

В случае, когда какое-нибудь из имён файлов указано неверно, следует выдать ошибку.

Кроме самой программы, следует написать автоматические тесты к ней.

В readme также необходимо добавить инструкцию по сборке и запуску Вашего консольного приложения.

**Comment by JohnKhandygo** [comment]
Давайте начнем с малого. 
- [ ] В java все классы принято называть в [UpperCamelCase](http://wiki.c2.com/?UpperCamelCase). Для того, чтобы "безболезненно" переименовать любую сущность (переменную, метод, поле, класс и т.д.) в idea необходимо:
  1. Щелчком  поставить курсор на имя сущности.
  2. Нажать Shift + f6.
  3. Изменить название необходимым образом.
  4. Нажать Enter.
- [ ] Парамтры из ввода так не считывают... Ну по крайней мере, не в Вашем случае. Обычно делают [вот так](https://docs.oracle.com/javase/tutorial/essential/environment/cmdLineArgs.html). Такой подход позволяет использовать различные библиотеки для разбора аргументов командной строки автоматическим образом. Насколько я понимаю, про [вот эту](http://args4j.kohsuke.org/sample.html) на лекциях рассказывали, она вполне подходит. Используя стороннюю библиотеку, Вы избавляете себя от необходимости тестировать кусок кода, который занимается разбором аргументов командной строки. 
- [ ] Вам скорее всего не нужен `FileLineIterator`: [`Scanner`](https://docs.oracle.com/javase/7/docs/api/java/util/Scanner.html) (который Вы используете для чтения строк из консоли) делает то же самое (даже тот же интерфейс `Iterator<String>` реализует). Кроме того, операции чтения и записи файла достаточно дорогостоящи в терминах быстродействия программы, поэтому хотелось бы избежать записи строк из консоли в промежуточный файл. Используя `Scanner` Вы обобщите обработку обоих случаев в один. Это значит меньше кода, меньше ошибок и, как следствие, меньше тестирования. 
- [ ] Что касается тестирования. Обычно ввод/вывод из файлов тестируют следующим образом:
  1. Заводите специальную папку, куда складываете все тестовые примеры входных файлов.
  2. Заводите специальную папку, куда складываете все тестовые примеры выходных файлов. 
  3. Каждый тест запускается на каком-то входном файле, его вывод сохраняется (в виде файла, например) и проверяется на равенство с содержимым соответствующего выходного файла. 
  4. Все файлы, созданные в процессе работы тестов удаляются.

**Comment by ADsty** [comment]
Извиняюсь за столь долгую задержку , связана она была с накопившимися проблемами в учебе. Теперь , когда большинство проблем решено , я могу снова переключиться на программирование . В это воскресенье я загружу новую версию проекта с исправленными комментариями , добавленными исключениями и javadoc и (я надеюсь) со скриптами сборки проекта

**Comment by JohnKhandygo** [comment]
Напишите, когда можно будет проверять.

**Comment by JohnKhandygo** [comment]
Не вижу каких-то существенных изменений. Для того, чтобы отловить большую часть ошибок, Вам следует написать побольше тестов. Из существенного:
- Структура проекта должна соответствовать [общепринятой](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html).
- Переменный лучше давать сколь-нибудь "говорящие".
- Неплохо было бы одну Вашу огромную функцию разбить на логические части и каждую вынести в отдельный метод. Чем длиннее функция, тем легче в ней запутаться. В принципе считается, что тело метода должно влезать на экран без скрола.

**Comment by ADsty** [comment]
Меня больше всего беспокоит библиотека args4j , так как с ней я работаю в первый раз и не уверен , что я правильно ее использую

**Comment by ADsty** [comment]
И еще мне довольно трудно пришлось со скриптами сборки , поэтому я бы еще хотел узнать как обстоят дела с ними и нужно ли вообще какие либо файлы из папки target отправлять , я ни у кого другого не заметил этой папки и решил тоже не отправлять , хотя там собранная программа моя лежит

**Comment by JohnKhandygo** [comment]
Вроде все правильно делаете, точно будет понятно после того, как проверите работу программы из консоли.

Из target ничего отправлять не надо, необходимо описать (инструкцией или скриптом) как собрать приложение и как его запустить.

**Comment by ADsty** [comment]
Вообщем исправил ошибку с тем , что у меня флаг u выполнял функции , которые должны выполняться и без него , вроде как теперь правильно организовал структуру проекта и немного подкорректировал файлы тестов под новый флаг u , который сравнивает строки с таблицей уже записанных строк и если находит идентичную , то пропускает ее , в будущем еще раз исправлю файлы , и добавлю конфигураций флагов. У меня возникла проблема , которую я никак не могу решить , а именно что делать при одновременно флагах -c и  -u ? Я записываю в файл строку с определенным значением параметра counterForC , но после того как я найду идентичную строку , исправить вновь прошлую строку , добавив к значению counterForC единицу , не получится. Можно ли оставить флаги -c и -u работать независимо друг от друга или же придется прежде чем записывать строки в файл обрабатывать их где то еще ? И не могли бы вы помочь с той ошибкой при сборке проекта? Полазал в поисковике насчет этой ошибки и не нашел ничего , что бы объяснило что мне нужно делать

**Comment by ADsty** [comment]
Ну и в принципе какие ошибки есть чтобы все исправить и перейти к 3 заданию

**Comment by JohnKhandygo** [comment]
Зачтено на 4.
