### ISSUE TITLE
Common issues

### ISSUE THREAD

**Issue by JohnKhandygo** [ADsty/uniq#2]
- [x] В Вашем проекте отсутствуют пакеты. Это, строго говоря, очень плохо, поскольку пакеты позволяют избегать коллизий в именах классов. [Здесь](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html) описан стандартный способ именования пакетов. В maven проектах также принято использовать `groupdId` (параметр в pom.xml) в качестве префикса для всех пакетов (иногда даже `groupId.artifactId`). Таким образом, для этих параметров в pom.xml принято использовать те же правила именования, что и для пакетов. 
- [x] Читай внимательно описание флага `-c`: если во входных данных было 2 одинаковые строки, в выходных данных должна быть одна с префиксом `2`. У Вас в этом случае в качестве префикса строки будет  использоваться `1`.
- [x] Вы, наверное не до конца поняли, что делает флаг `-u`. Например, я бы сказал, что в тестовом сценарии с файлом `FileOne` в выводе должны быть только две строки (1ая и 5ая), потому что все остальные одинаковы с учетом используемых параметров (то есть не уникальны). При таком раскладе не составляет труда реализовать поведение программы при одновременном указании флагов `-c` и `-u`.

**Comment by ADsty** [comment]
Исправил флаг -u  , теперь он работает следующим образом : строки записываются не в файл , а сначала в два ArrayList , в одном хранятся измененные флагами строки , в другом строки , которые в будущем будут записаны в выходной файл , в первом ArrayList я удаляю все уникальные строки и потом удаляю все строки из второго листа  , идентичные первым (изменив их с помощью флагов). Собственно данная реализация вроде как работает корректно. Новые конфигурации флагов в тесты я не вижу смысла добавлять , ибо флаги -i и -s достаточно просто реализованы , а флаги -c и -u я проверяю в большинстве нынешних тестов . Исправил вроде как все комментарии и наконец таки смог запустить без всяких ошибок программу , добавив в pom файл плагин maven-shade-plugin , единственная проблема связана с ошибкой NullPointerException при отсутствии outputFileName или inputFileName , нужно будет разобраться , но по крайней мере теперь программой можно пользоваться. Я так понимаю , что в readme нужно просто написать что программа собирается через Maven ?

**Comment by ADsty** [comment]
И насчет валидности хотел бы узнать : у меня при вызове некорректных флагов библиотека args4j выводит сообщение , что такого флага нет , нужно ли еще что-то добавить или нет?

**Comment by JohnKhandygo** [comment]
Все, что не отмечено галочками во всех открытых issue актуально. 

> И насчет валидации хотел бы узнать : у меня при вызове некорректных флагов библиотека args4j выводит сообщение , что такого флага нет , нужно ли еще что-то добавить или нет?

Нужно. В комментарии про валидацию я написал пример случая, который не обрабатывается.

> Исправил ошибку с исключением NullPointerException , проверил работу с консолью и вроде бы все работает

Как-то очень странно Вы ее исправили. А если у меня файл действительно называется outputFile?

- По поводу переделки полей классов в локальные переменные: в текущей реализации вся работа происходит за один вызов метода `work`, соответственно нет необходимости хранить такое сложное состояние объекта, поскольку оно не будет переиспользовано при дальнейшей работе с объектом и в то же время не требуется снаружи самого объекта. В то же время Ваш код стало намного сложнее понимать, потому что любое поле может использовано в любом месте внутри класса и для того, чтобы понять, правильно ли Вы заполняете какой-то список, необходимо просмотреть **все** места его использования внутри класса. То есть проблема заключается в том, что Вы используете **слишком широкую область видимости** для переменных.

**Comment by ADsty** [comment]
Исправил несколько комментариев : добавил исключения для случаев , если sNum не положительное число и если по пути inputFileName нет файла ; как то сразу не догадался как можно обойтись без присваивания файлу какого либо имени , но теперь исправил на сравнение null == outputFileName  , вроде исключение бросать не должно ; перекинул почти все поля в классе FlagsTest в локальные переменные , у меня есть идея как перекинуть еще iterator1 , но она выглядит не такой уж и хорошей (с помощью File.listFiles(); ) .

**Comment by JohnKhandygo** [comment]
Все, что не отмечено галочками во всех открытых issue актуально.

> перекинул почти все поля в классе FlagsTest в локальные переменные.

Так-то `file1` можно было оставить как поле, поскольку эта переменная используется в нескольких функциях. А вот `equals` да, нужен только в одной из них. При этом `iterator1` (или имя выходного файла) можно прокидывать в качестве аргумента в метод `comparingTwoFiles`... То есть Вы как бы вместо аргумента сделали общее поле, ну бред же.

**Comment by ADsty** [comment]
Исправил оставшееся вроде как

**Comment by ADsty** [comment]
Исправления на 5 уже не буду делать , ибо слишком мало времени осталось и я лучше переключусь на курсовой проект
