### ISSUE TITLE
Task 3.0

### ISSUE THREAD

**Issue by JohnKhandygo** [ADsty/uniq#5]
Если отбросить замечание, про ООП, то Вам осталось не так много исправить по первому заданию, поэтому предлагаю подумать над условием третьего. Есть несколько вариантов:
1. Получаете стандартное третье задание на написание графического приложения на Swing/JavaFX
2. Можете придумать свой вариант графического приложения, мы его обсудим и дополним/упростим по необходимости. По сложности должно получиться что-то типа многопользовательских шашек на одном компьютере.
3. Если Вам интересны какие-то конкретные направление в программировании (например, базы данных, web, Android) можно попробовать придумать задание с использованием этих технологий. 

Какой вариант Вам нравится больше всего?

**Comment by ADsty** [comment]
Честно говоря , я бы хотел что-то вроде своей RPG на Java сделать , но я уверен , что я не успею , поэтому давайте я сделаю стандартное задание какое нибудь .

**Comment by ADsty** [comment]
Пока что загрузил без тестов всю логику игры Реверси в новый репозиторий https://github.com/ADsty/reverse , воспользовался некоторыми идеями из игры fourinrow , которую нам показывали на первых лекциях , надеюсь что это не будет считаться как плагиат  , планирую закрыть последнюю работу на 3 , чтобы в общей сумме за курсовую получить оценку 4

**Comment by JohnKhandygo** [comment]
Перенес описание здния в новый репозиторий, все замечания будут появляться там.
